/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AmrL
 */
public class Livre extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public Livre() {     //c'est le constructeur de ma table
        initComponents();
        
        TableLivre(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldIsbn = new javax.swing.JTextField();
        textField_Id = new javax.swing.JTextField();
        textFieldTitre = new javax.swing.JTextField();
        textFieldLangueLivre = new javax.swing.JTextField();
        textFieldRecherche = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        buttonModifier = new javax.swing.JButton();
        buttonSupprimer = new javax.swing.JButton();
        buttonAjouter = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textFieldAnnee = new javax.swing.JTextField();
        btnActualiser = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        textField_NbPage = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textFieldDateAchat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textFieldNomDateParution = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textFieldIdAuteur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("JasmineUPC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE BOOKS");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 0, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("DATE PARUTION");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RECHERCHE:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("LANGUE-LIVRE:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ISBN:");

        textFieldIsbn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldIsbn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIsbnActionPerformed(evt);
            }
        });

        textField_Id.setBackground(new java.awt.Color(255, 0, 51));
        textField_Id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField_Id.setForeground(new java.awt.Color(255, 255, 255));
        textField_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_IdActionPerformed(evt);
            }
        });

        textFieldTitre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTitreActionPerformed(evt);
            }
        });

        textFieldLangueLivre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldLangueLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLangueLivreActionPerformed(evt);
            }
        });

        textFieldRecherche.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRechercheActionPerformed(evt);
            }
        });
        textFieldRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldRechercheKeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonModifier.setBackground(new java.awt.Color(204, 0, 204));
        buttonModifier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonModifier.setForeground(new java.awt.Color(255, 255, 255));
        buttonModifier.setText("MODIFIER");
        buttonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifierActionPerformed(evt);
            }
        });

        buttonSupprimer.setBackground(new java.awt.Color(204, 0, 204));
        buttonSupprimer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        buttonSupprimer.setText("SUPPRIMER");
        buttonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupprimerActionPerformed(evt);
            }
        });

        buttonAjouter.setBackground(new java.awt.Color(204, 0, 204));
        buttonAjouter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonAjouter.setForeground(new java.awt.Color(255, 255, 255));
        buttonAjouter.setText("AJOUTER");
        buttonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSupprimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buttonAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(buttonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buttonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(buttonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(186, Short.MAX_VALUE)))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("ANNEE:");

        textFieldAnnee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAnneeActionPerformed(evt);
            }
        });

        btnActualiser.setBackground(new java.awt.Color(0, 204, 0));
        btnActualiser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnActualiser.setForeground(new java.awt.Color(240, 240, 240));
        btnActualiser.setText("Actualiser");
        btnActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiserActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("NB-PAGE :");

        textField_NbPage.setBackground(new java.awt.Color(255, 0, 51));
        textField_NbPage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField_NbPage.setForeground(new java.awt.Color(255, 255, 255));
        textField_NbPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_NbPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_NbPageActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Titre :");

        textFieldDateAchat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldDateAchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDateAchatActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("DATE-ACHAT :");

        textFieldNomDateParution.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldNomDateParution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomDateParutionActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("ID-AUTEUR:");

        textFieldIdAuteur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldIdAuteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdAuteurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(textFieldLangueLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(186, 186, 186)
                            .addComponent(textFieldTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textField_NbPage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(textFieldDateAchat))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldIdAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNomDateParution, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldRecherche, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActualiser, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(215, 215, 215)
                    .addComponent(textField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1017, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1215, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1215, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(507, 507, 507)
                    .addComponent(jLabel10)
                    .addContainerGap(804, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(508, 508, 508)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(783, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldLangueLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(textFieldAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnActualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(textFieldRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_NbPage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(textFieldDateAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNomDateParution, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(textFieldIdAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(textField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(490, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(353, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(254, 254, 254)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(187, 187, 187)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(420, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(423, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(303, 303, 303)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(304, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1436, 686));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIsbnActionPerformed

    private void textField_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_IdActionPerformed

    private void textFieldTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTitreActionPerformed

    private void textFieldLangueLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLangueLivreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLangueLivreActionPerformed

    private void textFieldRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldRechercheActionPerformed

    private void buttonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupprimerActionPerformed
        
        try {
            Class.forName("org.sqlite.JDBC");
            con=DriverManager.getConnection("jdbc:sqlite:bdBiblio.db");   //lien vers la db  (connection à la db que j'ai créé)
            String sql="delete from livre where id=?";
            pst=con.prepareStatement(sql);
            
            pst.setString(1, textField_Id.getText());
           
            pst.executeUpdate(); // on lui dit d'exécuter la requete et d'insérer le tout dans ma table
            
            con.close();
            
            JOptionPane.showMessageDialog(null, "Suppression réussie");   // pour afficher un message
            
            TableLivre();
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_buttonSupprimerActionPerformed

    private void textFieldAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAnneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAnneeActionPerformed

    private void buttonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterActionPerformed
        
        try {
            Class.forName("org.sqlite.JDBC");
            con=DriverManager.getConnection("jdbc:sqlite:bdBiblio.db");   //lien vers la db  (connection à la db que j'ai créé)
            String sql="insert into livre (id, titre, langue, isbn, annee, nbpage, dateAchat, dateParution, idAuteur) values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst=con.prepareStatement(sql);
            
            pst.setString(1, textField_Id.getText());
            pst.setString(2, textFieldTitre.getText());
            pst.setString(3, textFieldLangueLivre.getText());
            pst.setString(4, textFieldIsbn.getText());
            pst.setString(5, textFieldAnnee.getText());
            pst.setString(6, textField_NbPage.getText());
            pst.setString(7, textFieldDateAchat.getText());
            pst.setString(8, textFieldNomDateParution.getText());
            pst.setString(9, textFieldIdAuteur.getText());
            
            pst.executeUpdate(); // on lui dit d'exécuter la requete et d'insérer le tout dans ma table
            
            con.close();
            
            JOptionPane.showMessageDialog(null, "Enregistrement réussi");   // pour afficher un message
            
            TableLivre();
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonAjouterActionPerformed

    private void buttonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifierActionPerformed
        
        try {
            Class.forName("org.sqlite.JDBC");
            con=DriverManager.getConnection("jdbc:sqlite:bdBiblio.db");   //lien vers la db  (connection à la db que j'ai créé)
            String sql="update livre  set titre=?, langue=?, isbn=?, annee=?, nbpage=?, dateAchat=?, dateParution=?, idAuteur=? where id=?";
            pst=con.prepareStatement(sql);
            
            pst.setString(9, textField_Id.getText());
            pst.setString(1, textFieldTitre.getText());
            pst.setString(2, textFieldLangueLivre.getText());
            pst.setString(3, textFieldIsbn.getText());
            pst.setString(4, textFieldAnnee.getText());
            pst.setString(5, textField_NbPage.getText());
            pst.setString(6, textFieldDateAchat.getText());
            pst.setString(7, textFieldNomDateParution.getText());
            pst.setString(8, textFieldIdAuteur.getText());
            
            pst.executeUpdate(); // on lui dit d'exécuter la requete et d'insérer le tout dans ma table
            
            con.close();
            
            JOptionPane.showMessageDialog(null, "Modification réussie");   // pour afficher un message
            
            TableLivre();
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonModifierActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        
        int i=jTable1.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        
        textField_Id.setText(model.getValueAt(i, 0).toString());
        textFieldTitre.setText(model.getValueAt(i, 1).toString());
        textFieldLangueLivre.setText(model.getValueAt(i, 2).toString());
        textFieldIsbn.setText(model.getValueAt(i, 3).toString());
        textFieldAnnee.setText(model.getValueAt(i, 4).toString());
        textField_NbPage.setText(model.getValueAt(i, 5).toString());
        textFieldDateAchat.setText(model.getValueAt(i, 6).toString());
        textFieldNomDateParution.setText(model.getValueAt(i, 7).toString());
        textFieldIdAuteur.setText(model.getValueAt(i, 8).toString());
        
    }//GEN-LAST:event_jTable1MouseReleased

    private void btnActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiserActionPerformed
        
        textField_Id.setText("");
        textFieldTitre.setText("");
        textFieldLangueLivre.setText("");
        textFieldIsbn.setText("");
        textFieldAnnee.setText("");
        textField_NbPage.setText("");
        textFieldDateAchat.setText("");
        textFieldNomDateParution.setText("");
        textFieldIdAuteur.setText("");
    }//GEN-LAST:event_btnActualiserActionPerformed

    private void textFieldRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldRechercheKeyReleased
        
        TableLivreRecherche(textFieldRecherche.getText());
    }//GEN-LAST:event_textFieldRechercheKeyReleased

    private void textField_NbPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_NbPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_NbPageActionPerformed

    private void textFieldDateAchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDateAchatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDateAchatActionPerformed

    private void textFieldNomDateParutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomDateParutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomDateParutionActionPerformed

    private void textFieldIdAuteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdAuteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdAuteurActionPerformed
    
    public void TableLivre(){
        
        String [] auteur= {"ID", "TITRE", "LANGUE-LIVRE" ,"ISBN", "ANNEE", "NB-PAGE", "DATE-ACHAT", "DATE-PARUTION", "ID-AUTEUR"};
        
        String [] afficher=new String[10];
        
        DefaultTableModel model= new DefaultTableModel(null, auteur); // on fait apparaitre le nom des colonnes
        
        String sql="select * from livre";
        
        try {
            
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:bdBiblio.db");
            
            Statement st=con.createStatement();
            rs= st.executeQuery(sql);
            
            while (rs.next()) {   //tant qu'il y a des choses à afficher il le fait)               
                
                afficher[0]= rs.getString("id");
                afficher[1]= rs.getString("titre");
                afficher[2]= rs.getString("langue");
                afficher[3]= rs.getString("isbn");
                afficher[4]= rs.getString("annee");
                afficher[5]= rs.getString("nbpage");
                afficher[6]= rs.getString("dateAchat");
                afficher[7]= rs.getString("dateParution");
                afficher[8]= rs.getString("idAuteur");
                
                model.addRow(afficher);
                
            }
            
            jTable1.setModel(model);           // nom de la variable du tableau que j'ai dans mon interface graphique
                    
            con.close();
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }
    
    public void TableLivreRecherche(String valeur){
        
        String [] livre= {"ID", "TITRE", "LANGUE-LIVRE" ,"ISBN", "ANNEE", "NB-PAGE", "DATE-ACHAT", "DATE-PARUTION", "ID-AUTEUR"};
        
        String [] afficher=new String[10];
        
        DefaultTableModel model= new DefaultTableModel(null, livre); // on fait apparaitre le nom des colonnes
        
        String sql="select * from livre where titre like '%"+valeur+"%'"; // on utilise like ici pour dire que toutes les personnes dont le nom contient s il va les afficher
        
        try {
            
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:bdBiblio.db");
            
            Statement st=con.createStatement();
            rs= st.executeQuery(sql);
            
            while (rs.next()) {   //tant qu'il y a des choses à afficher il le fait)               
                
                afficher[0]= rs.getString("id");
                afficher[1]= rs.getString("titre");
                afficher[2]= rs.getString("langue");
                afficher[3]= rs.getString("isbn");
                afficher[4]= rs.getString("annee");  
                afficher[5]= rs.getString("nbpage");
                afficher[6]= rs.getString("dateAchat");
                afficher[7]= rs.getString("dateParution");
                afficher[8]= rs.getString("idAuteur");
                
                model.addRow(afficher);
                
            }
            
            jTable1.setModel(model);           // nom de la variable du tableau que j'ai dans mon interface graphique
                    
            con.close();
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Livre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualiser;
    private javax.swing.JButton buttonAjouter;
    private javax.swing.JButton buttonModifier;
    private javax.swing.JButton buttonSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textFieldAnnee;
    private javax.swing.JTextField textFieldDateAchat;
    private javax.swing.JTextField textFieldIdAuteur;
    private javax.swing.JTextField textFieldIsbn;
    private javax.swing.JTextField textFieldLangueLivre;
    private javax.swing.JTextField textFieldNomDateParution;
    private javax.swing.JTextField textFieldRecherche;
    private javax.swing.JTextField textFieldTitre;
    private javax.swing.JTextField textField_Id;
    private javax.swing.JTextField textField_NbPage;
    // End of variables declaration//GEN-END:variables
}
